# Welcome

Hello! And welcome to my personal project to try and wrap my head further around Marchine Learning and Artificial Intellignce.  I've started various other courses in the past but due haven't had the time to see them all the way through to completion.  My current hiatus has allowed me the time to actually see things through - so here I am.  

Like any online technical tutorials the learning projects they provide tend to be clean and concise in order to quickly demonstrate the lessons being learned.  If there are mistakes they are (most likely) in there intentionally as a teaching moment.  With learning various other tecnology stacks throughout the course of my now decade long professional development career I can confirm that 'clean and concise' is not something frequently found real world, professional, programming projects.  Somewhere along the line, in some aspect, they all get a bit complex and convoluted.  They're never perfect. So much like when I wanted to solidify any of my web development skills I'm building my own project.

My goal here is to build something bigger than the project tutorials that don't cleanly reset after each module.  I want to have to pull my own data; investigate and clean it myself.  I want to go through the process of exploring it to find what connections and correlations are significant.  And then actually apply Machine Learning.

I also want this to be something that grows and evolves over time so that down the road I can, hopefully, look back on the variuos version and see how much I've learned and improved with the effort I put in.

If you're following along hopefully you find something interesting or insightful.  Or if you don't, or think I'm doing things wrong, let me know - improvement is always an option.

Either way - all the best.

-Reagan

July 2023

# Getting Started

## Packages

In the beginning there was no data.  There also weren't any packages in place, so let's get started there.

In [1]:
import pandas as pd
import numpy as np
import requests 
import json
import geopy.distance

## Data

Next is going to be getting data.  For a few years I had been web scraping from Basketball-Reference.com but in the last year or so they imposed rate limiting which made getting data harder for something at a scale like this.  As a result I found and got a promotion for a lifetime membership to NatStat.  As a result there are a plethora of APIs I can hit against to pull data, so we'll be doing that.  

For nat stat I have my IP Address registered with their site so there is no authentication/authorization process beyond that on the API calls themselves.  As a result this next cell will work only for me (or if you also have a subscription with them).  If that isn't the case and you want to see what I'm building then reach out to me - I'll send you the relevant CSV files and you can just skip the relevant API calls.

In [2]:
game_data = []
for year in range(2009, 2024):
    print(f'Getting data for year: {year}')
    nba_game_url = f'https://interst.at/game/nba/{year}'
    response = requests.get(nba_game_url)
    json_data = json.loads(response.text)
    for game in json_data['games'].items():
        game_id = game[0].split('_')[1]
        game_details = game[1]
        
        game_data.append({
            'Id': game_id,            
            'Season': year,
            'Date': game_details['gameday'],
            'Time': game_details['starttime'],
            'HomeTeamId': game_details['home']['id'],
            'HomeTeam': game_details['home']['code'],
            'HomeScore': game_details['home']['score'],
            'AwayTeamId': game_details['visitor']['id'],
            'AwayTeam': game_details['visitor']['code'],
            'AwayScore': game_details['visitor']['score'],
            'OverTime': game_details['score']['overtime'],
            'Latitude': game_details['venue']['latitude'],
            'Longitude': game_details['venue']['longitude'],
        })

Getting data for year: 2009
Getting data for year: 2010
Getting data for year: 2011
Getting data for year: 2012
Getting data for year: 2013
Getting data for year: 2014
Getting data for year: 2015
Getting data for year: 2016
Getting data for year: 2017
Getting data for year: 2018
Getting data for year: 2019
Getting data for year: 2020
Getting data for year: 2021
Getting data for year: 2022
Getting data for year: 2023

### Missing Data

Now that we've pulled everything from the API I'm going to manually add in the games that I know are missing.
This was a check that shows up later in the notebook but I want to keep things as quick as possible from top down so I'm going to add them in now, you'll see the check that helped find the missing data shortly

In [3]:
missing_games = [
    {               
        'Id': -1,            
        'Season': 2014,
        'Date': '2014-02-05',
        'Time': '22:00',
        'HomeTeamId': 15,
        'HomeTeam': 'SAC',
        'HomeScore': 109,
        'AwayTeamId': 10,
        'AwayTeam': 'TOR',
        'AwayScore': 101,
        'OverTime': 'N',
        'Latitude': '38.649110',
        'Longitude': '-121.518220',
    },
    {               
        'Id': -2,            
        'Season': 2014,
        'Date': '2014-02-05',
        'Time': '20:00',
        'HomeTeamId': 38,
        'HomeTeam': 'NOP',
        'HomeScore': 105,        
        'AwayTeamId': 6,
        'AwayTeam': 'ATL',
        'AwayScore': 100,
        'OverTime': 'N',
        'Latitude': '29.948910',
        'Longitude': '-90.082160',
    },
    {               
        'Id': -3,            
        'Season': 2014,
        'Date': '2014-02-05',
        'Time': '22:30',
        'HomeTeamId': 11,
        'HomeTeam': 'LAC',
        'HomeScore': 112,        
        'AwayTeamId': 16,
        'AwayTeam': 'MIA',
        'AwayScore': 116,
        'OverTime': 'N',
        'Latitude': '34.043150',
        'Longitude': '-118.267280',
    }, 
    {               
        'Id': -4,            
        'Season': 2014,
        'Date': '2014-02-05',
        'Time': '20:00',
        'HomeTeamId': 1,
        'HomeTeam': 'HOU',
        'HomeScore': 122,  
        'AwayTeamId': 14,
        'AwayTeam': 'PHO',
        'AwayScore': 108,
        'OverTime': 'N',
        'Latitude': '29.750580',
        'Longitude': '-95.362110',
    }, 
    {               
        'Id': -5,            
        'Season': 2014,
        'Date': '2014-02-05',
        'Time': '19:00',        
        'HomeTeamId': 20,
        'HomeTeam': 'WAS',
        'HomeScore': 118,          
        'AwayTeamId': 17,
        'AwayTeam': 'SAS',
        'AwayScore': 125,        
        'OverTime': '2OT',
        'Latitude': '38.898130',
        'Longitude': '-77.021060',
    },     
    {               
        'Id': -6,            
        'Season': 2014,
        'Date': '2014-02-05',
        'Time': '20:00', 
        'HomeTeamId': 31,
        'HomeTeam': 'MEM',
        'HomeScore': 96, 
        'AwayTeamId': 23,
        'AwayTeam': 'DAL',
        'AwayScore': 110,   
        'OverTime': 'N',
        'Latitude': '35.138110',
        'Longitude': '-90.050280',
    },     
    {               
        'Id': -7,            
        'Season': 2014,
        'Date': '2014-02-05',
        'Time': '20:00', 
        'HomeTeamId': 35,
        'HomeTeam': 'OKC',
        'HomeScore': 106, 
        'AwayTeamId': 2,
        'AwayTeam': 'MIN',
        'AwayScore': 97,   
        'OverTime': 'N',
        'Latitude': '35.463500',
        'Longitude': '-97.514900',
    },    
    {               
        'Id': -18,            
        'Season': 2014,
        'Date': '2014-02-05',
        'Time': '19:00',            
        'HomeTeamId': 28,
        'HomeTeam': 'PHI',
        'HomeScore': 108,             
        'AwayTeamId': 5,
        'AwayTeam': 'BOS',
        'AwayScore': 114,               
        'OverTime': 'N',
        'Latitude': '39.901190',
        'Longitude': '-75.171930',
    },    
    {               
        'Id': -19,            
        'Season': 2014,
        'Date': '2014-02-05',
        'Time': '19:00',           
        'HomeTeamId': 9,
        'HomeTeam': 'CLE',
        'HomeScore': 108,            
        'AwayTeamId': 27,
        'AwayTeam': 'LAL',
        'AwayScore': 119,            
        'OverTime': 'N',
        'Latitude': '41.496700',
        'Longitude': '-81.688380',
    },
    {               
        'Id': -20,            
        'Season': 2014,
        'Date': '2014-02-05',
        'Time': '21:00',          
        'HomeTeamId': 24,
        'HomeTeam': 'DEN',
        'HomeScore': 110,          
        'AwayTeamId': 7,
        'AwayTeam': 'MIL',
        'AwayScore': 100,         
        'OverTime': 'N',
        'Latitude': '39.748770',
        'Longitude': '-105.007420',
    },
    {               
        'Id': -21,            
        'Season': 2014,
        'Date': '2014-02-05',
        'Time': '19:00',         
        'HomeTeamId': 13,
        'HomeTeam': 'ORL',
        'HomeScore': 112,         
        'AwayTeamId': 22,
        'AwayTeam': 'DET',
        'AwayScore': 98,          
        'OverTime': 'N',
        'Latitude': '28.548770',
        'Longitude': '-81.386750',
    },
    {               
        'Id': -8,            
        'Season': 2019,
        'Date': '2018-10-27',
        'Time': '19:30',         
        'HomeTeamId': 9,
        'HomeTeam': 'CLE',
        'HomeScore': 107,         
        'AwayTeamId': 18,
        'AwayTeam': 'IND',
        'AwayScore': 119,          
        'OverTime': 'N',
        'Latitude': '41.496700',
        'Longitude': '-81.688380',
    },    
    {               
        'Id': -9,            
        'Season': 2019,
        'Date': '2018-11-02',
        'Time': '19:30',   
        'HomeTeamId': 36,
        'HomeTeam': 'BRK',
        'HomeScore': 111, 
        'AwayTeamId': 1,
        'AwayTeam': 'HOU',
        'AwayScore': 119,   
        'OverTime': 'N',
        'Latitude': '40.683320',
        'Longitude': '-73.976280',
    },       
    {               
        'Id': -10,            
        'Season': 2019,
        'Date': '2018-11-14',
        'Time': '19:00',        
        'HomeTeamId': 13,
        'HomeTeam': 'ORL',
        'HomeScore': 111,         
        'AwayTeamId': 28,
        'AwayTeam': 'PHI',
        'AwayScore': 106,          
        'OverTime': 'N',
        'Latitude': '28.548770',
        'Longitude': '-81.386750',
    },         
    
    {               
        'Id': -11,            
        'Season': 2019,
        'Date': '2018-12-17',
        'Time': '20:00',   
        
        'HomeTeamId': 35,
        'HomeTeam': 'OKC',
        'HomeScore': 121,    
        'AwayTeamId': 8,
        'AwayTeam': 'CHI',
        'AwayScore': 96,         
        'OverTime': 'N',
        'Latitude': '35.463500',
        'Longitude': '-97.514900',
    },         
    
    {               
        'Id': -12,            
        'Season': 2019,
        'Date': '2019-01-19',
        'Time': '20:30',         
        'HomeTeamId': 1,
        'HomeTeam': 'HOU',
        'HomeScore': 138,         
        'AwayTeamId': 27,
        'AwayTeam': 'LAL',
        'AwayScore': 134, 
        'OverTime': '1',
        'Latitude': '29.750580',
        'Longitude': '-95.362110',
    },           
    {               
        'Id': -13,            
        'Season': 2019,
        'Date': '2019-01-22',
        'Time': '20:30',  
        'HomeTeamId': 23,
        'HomeTeam': 'DAL',
        'HomeScore': 106, 
        'AwayTeamId': 11,
        'AwayTeam': 'LAC',
        'AwayScore': 98,         
        'OverTime': 'N',
        'Latitude': '32.7905300',
        'Longitude': '-96.810090',
    },                
    {               
        'Id': -14,            
        'Season': 2019,
        'Date': '2019-02-07',
        'Time': '22:30',
        'HomeTeamId': 4,
        'HomeTeam': 'POR',
        'HomeScore': 127, 
        'AwayTeamId': 17,
        'AwayTeam': 'SAS',
        'AwayScore': 118,   
        'OverTime': 'N',
        'Latitude': '45.531500',
        'Longitude': '-122.666810',
    },                
    {               
        'Id': -15,            
        'Season': 2019,
        'Date': '2019-02-23',
        'Time': '19:00',        
        'HomeTeamId': 3,
        'HomeTeam': 'CHH',
        'HomeScore': 115,         
        'AwayTeamId': 36,
        'AwayTeam': 'BRK',
        'AwayScore': 117,          
        'OverTime': 'N',
        'Latitude': '35.225140',
        'Longitude': '-80.839200',
    },                 
    {               
        'Id': -16,            
        'Season': 2019,
        'Date': '2019-03-02',
        'Time': '19:30',   
        'HomeTeamId': 16,
        'HomeTeam': 'MIA',
        'HomeScore': 117,  
        'AwayTeamId': 36,
        'AwayTeam': 'BRK',
        'AwayScore': 88,  
        'OverTime': 'N',
        'Latitude': '25.781430',
        'Longitude': '-80.187950',
    },               
    {               
        'Id': -17,            
        'Season': 2019,
        'Date': '2019-03-26',
        'Time': '20:00',          
        'HomeTeamId': 7,
        'HomeTeam': 'MIL',
        'HomeScore': 108,         
        'AwayTeamId': 1,
        'AwayTeam': 'HOU',
        'AwayScore': 94,          
        'OverTime': 'N',
        'Latitude': '43.045028',
        'Longitude': '-87.918167',
    },
    {               
        'Id': -22,            
        'Season': 2019,
        'Date': '2018-10-17',
        'Time': '19:30',             
        'HomeTeamId': 21,
        'HomeTeam': 'NYK',
        'HomeScore': 126,             
        'AwayTeamId': 6,
        'AwayTeam': 'ATL',
        'AwayScore': 107,              
        'OverTime': 'N',
        'Latitude': '40.750440',
        'Longitude': '-73.993510',
    },
    {               
        'Id': -23,            
        'Season': 2019,
        'Date': '2018-11-23',
        'Time': '20:00',          
        'HomeTeamId': 8,
        'HomeTeam': 'CHI',
        'HomeScore': 96,          
        'AwayTeamId': 16,
        'AwayTeam': 'MIA',
        'AwayScore': 103,            
        'OverTime': 'N',
        'Latitude': '41.880700',
        'Longitude': '-87.674290',
    },
    {               
        'Id': -24,            
        'Season': 2019,
        'Date': '2019-03-20',
        'Time': '22:00',     
        'HomeTeamId': 4,
        'HomeTeam': 'POR',
        'HomeScore': 126,   
        'AwayTeamId': 23,
        'AwayTeam': 'DAL',
        'AwayScore': 118,        
        'OverTime': 'N',
        'Latitude': '45.5315000',
        'Longitude': '-122.666810',
    },
    {               
        'Id': -25,            
        'Season': 2019,
        'Date': '2019-01-21',
        'Time': '17:30',     
        'HomeTeamId': 31,
        'HomeTeam': 'MEM',
        'HomeScore': 85,   
        'AwayTeamId': 38,
        'AwayTeam': 'NOP',
        'AwayScore': 105,  
        'OverTime': 'N',
        'Latitude': '35.138110',
        'Longitude': '-90.050280',
    },
    {               
        'Id': -26,            
        'Season': 2019,
        'Date': '2019-01-08',
        'Time': '21:00',             
        'HomeTeamId': 14,
        'HomeTeam': 'PHO',
        'HomeScore': 115, 
        'AwayTeamId': 15,
        'AwayTeam': 'SAC',
        'AwayScore': 111,  
        'OverTime': 'N',
        'Latitude': '33.445900',
        'Longitude': '-112.071210',
    },
    {               
        'Id': -27,            
        'Season': 2019,
        'Date': '2019-01-21',
        'Time': '14:00',   
        'HomeTeamId': 20,
        'HomeTeam': 'WAS',
        'HomeScore': 101, 
        'AwayTeamId': 22,
        'AwayTeam': 'DET',
        'AwayScore': 87,  
        'OverTime': 'N',
        'Latitude': '38.898130',
        'Longitude': '-77.021060',
    },
    {               
        'Id': -28,            
        'Season': 2019,
        'Date': '2018-12-03',
        'Time': '19:30',   
        'HomeTeamId': 25,
        'HomeTeam': 'GSW',
        'HomeScore': 128, 
        'AwayTeamId': 6,
        'AwayTeam': 'ATL',
        'AwayScore': 111, 
        'OverTime': 'N',
        'Latitude': '37.750260',
        'Longitude': '-122.202870',
    },
    {               
        'Id': -29,            
        'Season': 2019,
        'Date': '2018-12-23',
        'Time': '18:00',         
        'HomeTeamId': 5,
        'HomeTeam': 'BOS',
        'HomeScore': 119,         
        'AwayTeamId': 3,
        'AwayTeam': 'CHH',
        'AwayScore': 103,         
        'OverTime': 'N',
        'Latitude': '42.365340',
        'Longitude': '-71.062390',
    },
    {               
        'Id': -30,            
        'Season': 2019,
        'Date': '2019-02-08',
        'Time': '22:00',        
        'HomeTeamId': 15,
        'HomeTeam': 'SAC',
        'HomeScore': 102,         
        'AwayTeamId': 16,
        'AwayTeam': 'MIA',
        'AwayScore': 96,   
        'OverTime': 'N',
        'Latitude': '38.525231',
        'Longitude': '-121.525154',
    },
    {               
        'Id': -31,            
        'Season': 2019,
        'Date': '2019-02-13',
        'Time': '19:00', 
        'HomeTeamId': 18,
        'HomeTeam': 'IND',
        'HomeScore': 97, 
        'AwayTeamId': 7,
        'AwayTeam': 'MIL',
        'AwayScore': 106,         
        'OverTime': 'N',
        'Latitude': '39.763900',
        'Longitude': '-86.1557804',
    },
    {               
        'Id': -32,            
        'Season': 2019,
        'Date': '2019-02-14',
        'Time': '20:00',         
        'HomeTeamId': 38,
        'HomeTeam': 'NOP',
        'HomeScore': 131,         
        'AwayTeamId': 35,
        'AwayTeam': 'OKC',
        'AwayScore': 122,           
        'OverTime': 'N',
        'Latitude': '29.948910',
        'Longitude': '-90.082160',
    },
    {               
        'Id': -33,            
        'Season': 2019,
        'Date': '2019-03-24',
        'Time': '12:00',         
        'HomeTeamId': 21,
        'HomeTeam': 'NYK',
        'HomeScore': 113,          
        'AwayTeamId': 11,
        'AwayTeam': 'LAC',
        'AwayScore': 124, 
        'OverTime': 'N',
        'Latitude': '40.7504400',
        'Longitude': '-73.993510',
    },
]

for game in missing_games:
    game_data.append(game)

## Save Data

In [4]:
data = pd.DataFrame(game_data)   
data = data.sort_values('Date')
data.to_csv('Data/api_game_data.csv', index=False)

# Data Cleaning

Get basic information about the data

In [5]:
df = pd.read_csv('Data/api_game_data.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19167 entries, 0 to 19166
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          19167 non-null  int64
 1   Season      19167 non-null  int64
 2   Date        19167 non-null  object
 3   Time        19167 non-null  object
 4   HomeTeamId  19167 non-null  int64
 5   HomeTeam    19167 non-null  object
 6   HomeScore   19167 non-null  int64
 7   AwayTeamId  19167 non-null  int64
 8   AwayTeam    19167 non-null  object
 9   AwayScore   19167 non-null  int64
 10  OverTime    19167 non-null  object
 11  Latitude    19167 non-null  float64
 12  Longitude   19167 non-null  float64
dtypes: float64(2), int64(6), object(5)
memory usage: 1.9+ MB

In this case we have (as of Summer 2023) 20425 total games to work with between the 2007-2008 and the 2022-2023 NBA seasons.  

Most things seem to be in the correct format but having OverTime as an object and not some type of integer seems incorrect.  Lets take a look at that now.

In [7]:
print(np.sort(df["OverTime"].unique()))

['1' '2' '2OT' '3' '3OT' '4' '4OT' 'N' 'OT']

I don't want to just assume that '3' and '3OT' (and other OTs) are the same thing so lets take a look at those games just to make sure our data checks out.

In [8]:
ot_games = df.loc[((df.OverTime == '3') | (df.OverTime == '3OT'))]
ot_games

,Id,Season,Date,Time,HomeTeamId,HomeTeam,HomeScore,AwayTeamId,AwayTeam,AwayScore,OverTime,Latitude,Longitude
569,23584,2009,2009-01-14,{},25,GSW,133,15,SAC,135,3OT,37.750260,-122.202870
979,23998,2009,2009-03-14,13:00,16,MIA,140,26,UTA,129,3OT,25.781430,-80.187950
1271,24286,2009,2009-04-30,19:00,8,CHI,128,5,BOS,127,3OT,41.880700,-87.674290
2889,25911,2011,2010-12-01,19:00,36,NJN,120,35,OKC,123,3OT,40.733282,-74.171262
3557,26568,2011,2011-03-05,15:00,36,NJN,137,10,TOR,136,3OT,51.501227,0.004892
3681,26694,2011,2011-03-22,22:30,27,LAL,139,14,PHO,137,3,34.043150,-118.267280
3918,26932,2011,2011-05-09,{},31,MEM,123,35,OKC,133,3OT,35.138110,-90.050280
4035,27048,2012,2012-01-05,20:00,6,ATL,109,16,MIA,116,3,33.757230,-84.396360
4850,27866,2012,2012-04-16,21:00,26,UTA,123,23,DAL,121,3,40.768180,-111.901150
5113,28127,2013,2012-11-12,19:00,10,TOR,133,26,UTA,140,3OT,43.643300,-79.379140
5765,28778,2013,2013-02-10,18:00,5,BOS,118,24,DEN,114,3,42.365340,-71.062390
6266,29279,2013,2013-04-27,14:00,8,CHI,142,36,BRK,134,3OT,41.880700,-87.674290
6586,29596,2014,2013-12-02,20:00,8,CHI,128,38,NOP,131,3OT,41.880700,-87.674290
6899,29911,2014,2014-01-15,19:00,13,ORL,125,8,CHI,128,3OT,28.548770,-81.386750
7193,30192,2014,2014-02-27,19:00,10,TOR,129,20,WAS,134,3OT,43.643300,-79.379140
7813,30806,2015,2014-11-19,19:30,36,BRK,118,7,MIL,122,3OT,40.683320,-73.976280
8020,31024,2015,2014-12-17,20:30,17,SAS,116,31,MEM,117,3OT,29.427020,-98.437320
8040,31039,2015,2014-12-19,20:00,17,SAS,119,4,POR,129,3OT,29.427020,-98.437320
8672,31666,2015,2015-03-20,19:30,36,BRK,129,7,MIL,127,3,40.683320,-73.976280
12012,982512,2018,2017-12-15,19:00,28,PHI,117,35,OKC,119,3OT,39.901190,-75.171930
13375,985194,2019,2018-12-22,19:00,20,WAS,149,14,PHO,146,3OT,38.898130,-77.021060
13755,984232,2019,2019-02-13,19:00,9,CLE,139,36,BRK,148,3OT,41.496700,-81.688380
16808,1074614,2022,2021-11-26,22:30,27,LAL,137,15,SAC,141,3OT,34.043150,-118.267280
17261,1074716,2022,2022-01-29,20:00,16,MIA,120,10,TOR,124,3OT,25.781430,-80.187950

Spot checking some of these games (and I also looked at 4 vs 4OT games) both value types seem to accurrately represent the number of overtimes played in each game.

Now that we know the data is accurrate in both cases, lets make it consistent across the entire column.

In [9]:
def parse_overtime(overTime):
    if overTime == 'OT':
        return 1
    if overTime == '2OT':
        return 2
    if overTime == '3OT':
        return 3
    if overTime == '4OT':
        return 4
    else:
        return 0

In [10]:
df['OverTime'] = df['OverTime'].apply(lambda x: parse_overtime(x))

In [11]:
print(np.sort(df["OverTime"].unique()))
print(df.OverTime.dtype)

[0 1 2 3 4]
int64

That looks better.  Our values have been consolidated down to a single value and now that column has an integer data type.  I feel better about that column now.

Let's get some details about some specific columns (like scores) and see how they compare

In [12]:
print('Away Team:')
print(df["AwayScore"].describe())
print('Home Team:')
print(df["HomeScore"].describe())

Away Team:
count    19167.000000
mean       103.203005
std         13.434485
min         56.000000
25%         94.000000
50%        103.000000
75%        112.000000
max        196.000000
Name: AwayScore, dtype: float64
Home Team:
count    19167.000000
mean       105.847185
std         13.321335
min         59.000000
25%         97.000000
50%        105.000000
75%        115.000000
max        175.000000
Name: HomeScore, dtype: float64

I think it's safe to say there are no surprises here.  The mean score for the home team being higher makes sense to me, that's a home court advantage coming into play right there.

The interquartile range for both home and away teams falls in the range I would expect for an NBA game. Doesn't appear to be any kind of major outlier there.  Also I feel like the standard deviation being so close for both home and away games bodes well for what we're going to build here.  

Let's carry on.

Lets give our teams a look to see if there's anything amiss.  We should see the same values for both home and away teams since there isn't a team playing just home games.

In [13]:
print(np.sort(df["HomeTeam"].unique()))
print(np.sort(df["AwayTeam"].unique()))

['ATL' 'BOS' 'BRK' 'CHH' 'CHI' 'CLE' 'DAL' 'DEN' 'DET' 'ECONF' 'GSW' 'HOU'
 'IND' 'LAC' 'LAL' 'MEM' 'MIA' 'MIL' 'MIN' 'NJN' 'NOH' 'NOP' 'NYK' 'OKC'
 'ORL' 'PHI' 'PHO' 'POR' 'SAC' 'SAS' 'TOR' 'UTA' 'WAS' 'WCONF']
['ATL' 'BOS' 'BRK' 'CHH' 'CHI' 'CLE' 'DAL' 'DEN' 'DET' 'ECONF' 'GSW' 'HOU'
 'IND' 'LAC' 'LAL' 'MEM' 'MIA' 'MIL' 'MIN' 'NJN' 'NOH' 'NOP' 'NYK' 'OKC'
 'ORL' 'PHI' 'PHO' 'POR' 'SAC' 'SAS' 'TOR' 'UTA' 'WAS' 'WCONF']

We have the same teams in both home and away so that's good but there is one small problem in the teams we have.

For what we're working on I'm not going to be paying attention to all star games so anything where WCONF (Western Conference) is playing ECONF (Eastern Conference) can be removed.

Let's do that now.

In [14]:
all_star_teams = ['ECONF', 'WCONF']
df = df[~df.HomeTeam.isin(all_star_teams)]

In [15]:
print(np.sort(df["HomeTeam"].unique()))
print(np.sort(df["AwayTeam"].unique()))

['ATL' 'BOS' 'BRK' 'CHH' 'CHI' 'CLE' 'DAL' 'DEN' 'DET' 'GSW' 'HOU' 'IND'
 'LAC' 'LAL' 'MEM' 'MIA' 'MIL' 'MIN' 'NJN' 'NOH' 'NOP' 'NYK' 'OKC' 'ORL'
 'PHI' 'PHO' 'POR' 'SAC' 'SAS' 'TOR' 'UTA' 'WAS']
['ATL' 'BOS' 'BRK' 'CHH' 'CHI' 'CLE' 'DAL' 'DEN' 'DET' 'GSW' 'HOU' 'IND'
 'LAC' 'LAL' 'MEM' 'MIA' 'MIL' 'MIN' 'NJN' 'NOH' 'NOP' 'NYK' 'OKC' 'ORL'
 'PHI' 'PHO' 'POR' 'SAC' 'SAS' 'TOR' 'UTA' 'WAS']

That's better.  Now our data is a little bit cleaner.

# Remove Duplicates
This next bit of cleaning came from running through the distance and record calculation (coming up soon) and spot checking the results.  When looking at the tail end of data when filtered for specific seasons and teams I was noticing that some teams were coming up to 83 total games, even if they didn't make the playoffs.  This is a prime example of understanding hte content area is helpful - I know that there's only ever 82 games in a regular season so something must be wrong. The one that keyed me in was that the 2022-2023 Portland Trailblazers had 83 games despite finishing the season 16 games under .500 and not having a shot at the playoffs. 

That's when I just had to do some manual digging to figure out where the error was.  I looked at the full table of games that I was getting back from the API for the 2022-2023 Trailblazers and saw there were some games that had the same scores between the same teams on back to back days.  That seemed slightly off so I created a query to look at any potential duplicates based on opponent and score.

In [16]:
dupes = df[df.duplicated(subset=['Season','HomeTeamId','HomeScore','AwayTeamId','AwayScore'], keep=False)]
dupes

,Id,Season,Date,Time,HomeTeamId,HomeTeam,HomeScore,AwayTeamId,AwayTeam,AwayScore,OverTime,Latitude,Longitude
472,23493,2009,2009-01-02,22:30,27,LAL,113,26,UTA,100,0,34.043150,-118.267280
1236,24253,2009,2009-04-19,15:00,27,LAL,113,26,UTA,100,0,34.043150,-118.267280
4318,27336,2012,2012-02-08,19:00,10,TOR,99,7,MIL,105,0,43.643300,-79.379140
4544,27564,2012,2012-03-11,18:00,10,TOR,99,7,MIL,105,0,43.643300,-79.379140
8894,31892,2015,2015-04-22,22:30,11,LAC,107,17,SAS,111,0,34.043150,-118.267280
8913,31912,2015,2015-04-28,{},11,LAC,107,17,SAS,111,0,34.043150,-118.267280
13042,985066,2019,2018-11-05,20:00,35,OKC,122,38,NOP,116,0,35.463500,-97.514900
13612,985078,2019,2019-01-24,20:00,35,OKC,122,38,NOP,116,0,35.463500,-97.514900
16021,1042373,2021,2021-03-27,21:00,26,UTA,126,31,MEM,110,0,40.768180,-111.901150
16469,1042427,2021,2021-06-02,21:30,26,UTA,126,31,MEM,110,0,40.768180,-111.901150
16474,1042422,2021,2021-06-03,20:00,4,POR,115,24,DEN,126,0,39.748770,-105.007420
16476,1042423,2021,2021-06-04,23:59,4,POR,115,24,DEN,126,0,39.748770,-105.007420
16490,1042445,2021,2021-06-13,20:00,24,DEN,118,14,PHO,125,0,39.748770,-105.007420
16495,1042446,2021,2021-06-15,{},24,DEN,118,14,PHO,125,0,33.445900,-112.071210
17042,1074671,2022,2021-12-31,20:00,31,MEM,118,17,SAS,105,0,35.138110,-90.050280
17275,1074994,2022,2022-01-31,19:30,6,ATL,100,10,TOR,106,0,33.757230,-84.396360
17281,1073807,2022,2022-02-01,19:30,6,ATL,100,10,TOR,106,0,33.757230,-84.396360
17438,1075309,2022,2022-02-28,20:00,31,MEM,118,17,SAS,105,0,35.138110,-90.050280
18808,1076771,2023,2023-03-05,19:30,20,WAS,111,7,MIL,117,0,38.898130,-77.021060
18815,1076769,2023,2023-03-06,19:00,22,DET,104,4,POR,110,0,42.341172,-83.054911
18820,1076535,2023,2023-03-06,19:00,20,WAS,111,7,MIL,117,0,38.898130,-77.021060
18828,1076152,2023,2023-03-07,19:00,22,DET,104,4,POR,110,0,42.341172,-83.054911
18852,1076032,2023,2023-03-11,20:00,31,MEM,112,23,DAL,108,0,35.138110,-90.050280
18919,1076036,2023,2023-03-20,20:00,31,MEM,112,23,DAL,108,0,35.138110,-90.050280

From this we can see that there are a handful of games that match this criteria.

To ensure my data is as clean as possible and manually went through and checked the validity of these games to see if any were in fact duplicates. Most were legitimate - just two teams reaching the same outcome in different games throughout the course of a season.  But there were 5 that were duplicates in the data and needed to be removed:

In [17]:
df = df.loc[df["Id"] != 1076152 ]
df = df.loc[df["Id"] != 1076535 ]
df = df.loc[df["Id"] != 1073807 ]
df = df.loc[df["Id"] != 1042446 ]
df = df.loc[df["Id"] != 1042423 ]

From the spot checking that you'll see later on I confirmed that this did fix the issue I was having but I'd rather clean it up once before the next step now that I figured it out instead of going through a few iterations to show the incorrect data, the 83 games, the list of the games within a season to show the duplicates, resetting the data, removing the duplicates, then going through it again.  

I spent two days working out this issue - now I'm just going to fix it first!

## Some Data Processing

I have the basic game information for each game in the season but I want to keep track of things as the seasons progressed.  Namely I want to track the wins, losses, (and resulting from that total games played and win percentage), as well as how far any away team has traveled on any given road trip.  For this I wanted it cumulative - if the Knicks do a 6 game West Coast road trip I want to calulate the travel from NY to game 1, then add the distance from game 1 to game 2, and so on until they're home again.

This requires iterating through all of the games by season and performing some calculations.

First let's define the update function to update any given record, and the SeasonStanding class that will keep track of a team's position throughout the seasons:

In [18]:
def update_record(df, index, isHome, standings):
    if isHome is True:
        df.at[index, 'HomeWins'] = standings.wins
        df.at[index, 'HomeLosses'] = standings.losses
        df.at[index, 'HomeStreak'] = standings.streak
        df.at[index, 'HomeGamesPlayed'] = standings.games
        df.at[index, 'HomeWinPercentage'] = standings.percentage
    else:
        df.at[index, 'AwayWins'] = standings.wins
        df.at[index, 'AwayLosses'] = standings.losses
        df.at[index, 'AwayStreak'] = standings.streak
        df.at[index, 'AwayGamesPlayed'] = standings.games
        df.at[index, 'AwayWinPercentage'] = standings.percentage

In [19]:
class SeasonStandings:
    def __init__(self):
        self.wins = 0
        self.losses = 0
        self.streak = 0
        self.games = 0
        self.percentage = 0

    def add_game(self, team_win):
        if team_win is True:
            self.wins += 1
            if self.streak <= 0:
                self.streak = 1
            else:
                self.streak += 1
        else:
            self.losses += 1
            if self.streak >= 0:
                self.streak = -1
            else:
                self.streak -= 1
        self.percentage = self.wins / (self.wins + self.losses)
        self.games = (self.wins + self.losses)

This is the loop that will iterate through each team and their games to determine the team's record going into each game and how far the away team has traveled since their last home game.

In [20]:
# Loop through every team
for team in np.sort(df["HomeTeam"].unique()):
    # In each loop it's going to start at the very beginning so no previous game and it's a brand new season with no distance traveled
    previousGame = None 
    current_standings = SeasonStandings()
    travelDistance = 0
    
    # Get all the games for the specific team
    team_games = df.loc[(df.HomeTeam == team) | (df.AwayTeam == team)]
    for index, row in team_games.iterrows():
        if previousGame is None:
            #new season and since they had a whole offseason to prepare I won't be too concerned about the distance traveled for this game
            #Also down the road I expect to remove the first 10 or so games from each season to allow players to settle in before trying to predict anything
            df.at[index, 'TravelDistance'] = 0
        if previousGame is not None:
            #If it's a new season reset the SeasonStandings Class and our travel distance.
            if previousGame.Season != row.Season:
                df.at[index, 'TravelDistance'] = 0
                current_standings = SeasonStandings()
                travelDistance = 0
        
        #Check to see if this team is home or away for this particular game and update their record going into this game
        is_home = row.HomeTeam == team     
        update_record(df, index, is_home, current_standings)

        #Check to see - did the team we're looking at currently win the game we're currently looking at?
        if is_home is True:
            team_win = row.HomeScore > row.AwayScore
        else:            
            team_win = row.HomeScore < row.AwayScore

        #Updating the standings accordingly
        current_standings.add_game(team_win)

        #One last check to make sure that if there is a previous game from this season we update the travel distance accordingly
        if previousGame is not None:
            if previousGame.Season is not row.Season:
                if is_home is True:
                    travelDistance = 0
                else:
                    previous_coord = (previousGame.Latitude, previousGame.Longitude)
                    current_coord = (row.Latitude, row.Longitude)
        
                    travel = geopy.distance.geodesic(previous_coord, current_coord).mi
                    travelDistance += travel;

                    team_games.at[index, 'TravelDistance'] = travelDistance
                    df.at[index, 'TravelDistance'] = travelDistance
        
        #Then we set the previous game to this one so that we have what we need to calculate against for the next one
        previousGame = row

C:\Users\Micha\AppData\Local\Temp\ipykernel_24312\3335592146.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  team_games.at[index, 'TravelDistance'] = travelDistance

These next two cells are to spot check values for any team during a specific season.  This was the easiest way (in my opinion) to follow the progression throughout the season and check for any errors in the process.  This is how I found duplicate rows in the data and was able to determine that my distance calculations were working correctly.

In [21]:
team = "NYK"
team_games = df.loc[((df.HomeTeam == team) | (df.AwayTeam == team)) & (df.Season == 2019)]
for index, row in team_games.iterrows():
    if row.HomeTeam == team:
        print(f'{row.Date}  vs {row.AwayTeam} ({row.HomeWins}-{row.HomeLosses})')
    else:
        print(f'{row.Date}  @ {row.HomeTeam} ({row.AwayWins}-{row.AwayLosses})')
    # print(f'{row.Date} {row.AwayTeam}:{row.AwayScore} ({row.AwayWins}-{row.AwayLosses} : {row.AwayWinPercentage}) - Streak: {row.AwayStreak} @ {row.HomeTeam}:{row.HomeScore} ({row.HomeWins} - {row.HomeLosses}  : {row.HomeWinPercentage})  - Streak: {row.HomeStreak} Distance: {row.TravelDistance} ')

2018-10-17  vs ATL (0.0-0.0)
2018-10-19  @ BRK (1.0-0.0)
2018-10-20  vs BOS (1.0-1.0)
2018-10-22  @ MIL (1.0-2.0)
2018-10-24  @ MIA (1.0-3.0)
2018-10-26  vs GSW (1.0-4.0)
2018-10-29  vs BRK (1.0-5.0)
2018-10-31  vs IND (2.0-5.0)
2018-11-02  @ DAL (2.0-6.0)
2018-11-04  @ WAS (3.0-6.0)
2018-11-05  vs CHI (3.0-7.0)
2018-11-07  @ ATL (3.0-8.0)
2018-11-10  @ TOR (4.0-8.0)
2018-11-11  vs ORL (4.0-9.0)
2018-11-14  @ OKC (4.0-10.0)
2018-11-16  @ NOP (4.0-11.0)
2018-11-18  @ ORL (4.0-12.0)
2018-11-20  vs POR (4.0-13.0)
2018-11-21  @ BOS (4.0-14.0)
2018-11-23  vs NOP (5.0-14.0)
2018-11-25  @ MEM (6.0-14.0)
2018-11-27  @ DET (7.0-14.0)
2018-11-28  @ PHI (7.0-15.0)
2018-12-01  vs MIL (7.0-16.0)
2018-12-03  vs WAS (8.0-16.0)
2018-12-06  @ BOS (8.0-17.0)
2018-12-08  vs BRK (8.0-18.0)
2018-12-09  vs CHH (8.0-19.0)
2018-12-12  @ CLE (8.0-20.0)
2018-12-14  @ CHH (8.0-21.0)
2018-12-16  @ IND (9.0-21.0)
2018-12-17  vs PHO (9.0-22.0)
2018-12-19  @ PHI (9.0-23.0)
2018-12-21  vs ATL (9.0-24.0)
2018-12-25  vs MIL (9.0-25.0)
2018-12-27  @ MIL (9.0-26.0)
2018-12-29  @ UTA (9.0-27.0)
2019-01-01  @ DEN (9.0-28.0)
2019-01-04  @ LAL (9.0-29.0)
2019-01-07  @ POR (10.0-29.0)
2019-01-08  @ GSW (10.0-30.0)
2019-01-11  vs IND (10.0-31.0)
2019-01-13  vs PHI (10.0-32.0)
2019-01-17  @ WAS (10.0-33.0)
2019-01-21  vs OKC (10.0-34.0)
2019-01-23  vs HOU (10.0-35.0)
2019-01-25  @ BRK (10.0-36.0)
2019-01-27  vs MIA (10.0-37.0)
2019-01-28  @ CHH (10.0-38.0)
2019-01-30  vs DAL (10.0-39.0)
2019-02-01  vs BOS (10.0-40.0)
2019-02-03  vs MEM (10.0-41.0)
2019-02-05  vs DET (10.0-42.0)
2019-02-08  @ DET (10.0-43.0)
2019-02-09  vs TOR (10.0-44.0)
2019-02-11  @ CLE (10.0-45.0)
2019-02-13  vs PHI (10.0-46.0)
2019-02-14  @ ATL (10.0-47.0)
2019-02-22  vs MIN (11.0-47.0)
2019-02-24  vs SAS (11.0-48.0)
2019-02-26  vs ORL (12.0-48.0)
2019-02-28  vs CLE (13.0-48.0)
2019-03-03  @ LAC (13.0-49.0)
2019-03-04  @ SAC (13.0-50.0)
2019-03-06  @ PHO (13.0-51.0)
2019-03-09  vs SAC (13.0-52.0)
2019-03-10  @ MIN (13.0-53.0)
2019-03-12  @ IND (13.0-54.0)
2019-03-15  @ SAS (13.0-55.0)
2019-03-17  vs LAL (13.0-56.0)
2019-03-18  @ TOR (14.0-56.0)
2019-03-20  vs UTA (14.0-57.0)
2019-03-22  vs DEN (14.0-58.0)
2019-03-24  vs LAC (14.0-59.0)
2019-03-28  vs TOR (14.0-60.0)
2019-03-30  vs MIA (14.0-61.0)
2019-04-01  vs CHI (14.0-62.0)
2019-04-03  @ ORL (15.0-62.0)
2019-04-05  @ HOU (15.0-63.0)
2019-04-07  vs WAS (15.0-64.0)
2019-04-09  @ CHI (16.0-64.0)
2019-04-10  vs DET (17.0-64.0)

In [22]:
team = "OKC"
team_games = df.loc[((df.HomeTeam == team) | (df.AwayTeam == team)) & (df.Season == 2014)]
team_games[['Season','Date','HomeTeam', 'HomeScore','HomeWins', 'HomeLosses', 'HomeGamesPlayed', 'HomeStreak','AwayTeam', 'AwayScore','AwayWins', 'AwayLosses','AwayWinPercentage', 'AwayGamesPlayed','AwayStreak', 'TravelDistance']].tail(55)

,Season,Date,HomeTeam,HomeScore,HomeWins,HomeLosses,HomeGamesPlayed,HomeStreak,AwayTeam,AwayScore,AwayWins,AwayLosses,AwayWinPercentage,AwayGamesPlayed,AwayStreak,TravelDistance
7009,2014,2014-01-29,MIA,95,32.0,12.0,44.0,3.0,OKC,112,36.0,10.0,0.782609,46.0,8.0,1226.012955
7019,2014,2014-01-31,BRK,95,20.0,23.0,43.0,-1.0,OKC,120,37.0,10.0,0.787234,47.0,9.0,2313.407332
7024,2014,2014-02-01,WAS,96,22.0,23.0,45.0,-1.0,OKC,81,38.0,10.0,0.791667,48.0,10.0,2516.928274
7046,2014,2014-02-03,OKC,86,38.0,11.0,49.0,-1.0,MEM,77,26.0,20.0,0.565217,46.0,6.0,422.361473
7055,2014,2014-02-05,OKC,106,39.0,11.0,50.0,1.0,MIN,97,24.0,24.0,0.500000,48.0,1.0,693.518001
7068,2014,2014-02-07,ORL,103,14.0,37.0,51.0,1.0,OKC,102,40.0,11.0,0.784314,51.0,2.0,1058.105417
7084,2014,2014-02-09,OKC,112,40.0,12.0,52.0,-1.0,NYK,100,20.0,30.0,0.400000,50.0,1.0,1328.125757
7097,2014,2014-02-11,POR,95,36.0,15.0,51.0,1.0,OKC,98,41.0,12.0,0.773585,53.0,1.0,1487.079465
7116,2014,2014-02-13,LAL,103,18.0,34.0,52.0,-2.0,OKC,107,42.0,12.0,0.777778,54.0,2.0,2313.196757
7141,2014,2014-02-20,OKC,81,43.0,12.0,55.0,3.0,MIA,103,38.0,14.0,0.730769,52.0,3.0,5728.224027
7161,2014,2014-02-23,OKC,117,43.0,13.0,56.0,-1.0,LAC,125,37.0,20.0,0.649123,57.0,-2.0,2027.263137
7181,2014,2014-02-26,OKC,104,43.0,14.0,57.0,-2.0,CLE,114,22.0,36.0,0.379310,58.0,-3.0,951.688298
7199,2014,2014-02-28,OKC,113,43.0,15.0,58.0,-3.0,MEM,107,32.0,24.0,0.571429,56.0,1.0,422.361473
7210,2014,2014-03-02,OKC,116,44.0,15.0,59.0,1.0,CHH,99,27.0,31.0,0.465517,58.0,-1.0,1521.838490
7230,2014,2014-03-04,OKC,125,45.0,15.0,60.0,2.0,PHI,92,15.0,45.0,0.250000,60.0,-14.0,1917.099298
7242,2014,2014-03-06,PHO,128,35.0,25.0,60.0,-1.0,OKC,122,46.0,15.0,0.754098,61.0,3.0,841.873893
7266,2014,2014-03-09,LAL,114,21.0,42.0,63.0,-3.0,OKC,110,46.0,16.0,0.741935,62.0,-1.0,1200.931931
7281,2014,2014-03-11,OKC,106,46.0,17.0,63.0,-2.0,HOU,98,44.0,19.0,0.698413,63.0,5.0,413.173473
7296,2014,2014-03-13,OKC,131,47.0,17.0,64.0,1.0,LAL,102,22.0,42.0,0.343750,64.0,1.0,1182.547495
7318,2014,2014-03-16,OKC,86,48.0,17.0,65.0,2.0,DAL,109,39.0,27.0,0.590909,66.0,1.0,2924.424318
7323,2014,2014-03-17,CHI,85,37.0,29.0,66.0,2.0,OKC,97,48.0,18.0,0.727273,66.0,-1.0,691.344487
7348,2014,2014-03-20,CLE,95,26.0,42.0,68.0,-2.0,OKC,102,49.0,18.0,0.731343,67.0,1.0,1002.070861
7350,2014,2014-03-21,TOR,118,38.0,29.0,67.0,1.0,OKC,119,50.0,18.0,0.735294,68.0,2.0,1191.352883
7379,2014,2014-03-24,OKC,117,51.0,18.0,69.0,3.0,DEN,96,32.0,38.0,0.457143,70.0,1.0,505.993997
7386,2014,2014-03-25,DAL,128,42.0,29.0,71.0,-1.0,OKC,119,52.0,18.0,0.742857,70.0,4.0,188.611199
7410,2014,2014-03-28,OKC,94,52.0,19.0,71.0,-1.0,SAC,81,25.0,46.0,0.352113,71.0,-1.0,1340.720876
7423,2014,2014-03-30,OKC,116,53.0,19.0,72.0,1.0,UTA,96,23.0,50.0,0.315068,73.0,-3.0,2010.067572
7455,2014,2014-04-03,OKC,106,54.0,19.0,73.0,2.0,SAS,94,59.0,16.0,0.786667,75.0,19.0,419.425908
7462,2014,2014-04-04,HOU,111,49.0,25.0,74.0,-3.0,OKC,107,55.0,19.0,0.743243,74.0,3.0,413.173473
7476,2014,2014-04-06,PHO,122,45.0,31.0,76.0,1.0,OKC,115,55.0,20.0,0.733333,75.0,-1.0,1429.580960
7487,2014,2014-04-08,SAC,92,27.0,50.0,77.0,-2.0,OKC,107,55.0,21.0,0.723684,76.0,-2.0,2068.151268
7495,2014,2014-04-09,LAC,101,55.0,23.0,78.0,1.0,OKC,107,56.0,21.0,0.727273,77.0,1.0,2433.791625
7511,2014,2014-04-11,OKC,116,57.0,21.0,78.0,2.0,NOP,94,32.0,46.0,0.410256,78.0,-6.0,575.784338
7529,2014,2014-04-13,IND,102,54.0,26.0,80.0,-1.0,OKC,97,58.0,21.0,0.734177,79.0,3.0,689.441424
7534,2014,2014-04-14,NOP,101,32.0,48.0,80.0,-8.0,OKC,89,58.0,22.0,0.725000,80.0,-1.0,1401.651816
7549,2014,2014-04-16,OKC,112,58.0,23.0,81.0,-2.0,DET,111,29.0,52.0,0.358025,81.0,-3.0,913.237136
7562,2014,2014-04-19,OKC,100,59.0,23.0,82.0,1.0,MEM,86,50.0,32.0,0.609756,82.0,5.0,422.361473
7568,2014,2014-04-21,OKC,105,60.0,23.0,83.0,2.0,MEM,111,50.0,33.0,0.602410,83.0,-1.0,422.361473
7578,2014,2014-04-24,MEM,98,51.0,33.0,84.0,1.0,OKC,95,60.0,24.0,0.714286,84.0,-1.0,422.361473
7584,2014,2014-04-26,MEM,89,52.0,33.0,85.0,2.0,OKC,92,60.0,25.0,0.705882,85.0,-2.0,422.361473
7593,2014,2014-04-29,OKC,99,61.0,25.0,86.0,1.0,MEM,100,52.0,34.0,0.604651,86.0,-1.0,422.361473
7601,2014,2014-05-01,MEM,84,53.0,34.0,87.0,1.0,OKC,104,61.0,26.0,0.701149,87.0,-1.0,422.361473
7606,2014,2014-05-03,OKC,120,62.0,26.0,88.0,1.0,MEM,109,53.0,35.0,0.602273,88.0,-1.0,422.361473
7610,2014,2014-05-05,OKC,105,63.0,26.0,89.0,2.0,LAC,122,61.0,28.0,0.685393,89.0,1.0,1182.547495
7614,2014,2014-05-07,OKC,112,63.0,27.0,90.0,-1.0,LAC,101,62.0,28.0,0.688889,90.0,2.0,1182.547495
7618,2014,2014-05-09,LAC,112,62.0,29.0,91.0,-1.0,OKC,118,64.0,27.0,0.703297,91.0,1.0,1182.547495
7622,2014,2014-05-11,LAC,101,62.0,30.0,92.0,-2.0,OKC,99,65.0,27.0,0.706522,92.0,2.0,1182.547495
7627,2014,2014-05-13,OKC,105,65.0,28.0,93.0,-1.0,LAC,104,63.0,30.0,0.677419,93.0,1.0,1182.547495
7630,2014,2014-05-15,LAC,98,63.0,31.0,94.0,-1.0,OKC,104,66.0,28.0,0.702128,94.0,1.0,1182.547495
7633,2014,2014-05-19,SAS,122,70.0,24.0,94.0,1.0,OKC,105,67.0,28.0,0.705263,95.0,2.0,2390.519651
7635,2014,2014-05-21,SAS,112,71.0,24.0,95.0,2.0,OKC,77,67.0,29.0,0.697917,96.0,-1.0,2390.519651
7637,2014,2014-05-25,OKC,106,67.0,30.0,97.0,-2.0,SAS,97,72.0,24.0,0.750000,96.0,3.0,419.425908
7639,2014,2014-05-27,OKC,105,68.0,30.0,98.0,1.0,SAS,92,72.0,25.0,0.742268,97.0,-1.0,419.425908
7641,2014,2014-05-29,SAS,117,72.0,26.0,98.0,-2.0,OKC,89,69.0,30.0,0.696970,99.0,2.0,419.425908
7643,2014,2014-05-31,OKC,107,69.0,31.0,100.0,-1.0,SAS,112,73.0,26.0,0.737374,99.0,1.0,419.425908

Do a check to make sure all of the columns have values in all of the columns.  Initially I was getting issues with how my loop was processing the first game of a season so there were some na values where there should have been 0 as a value instead. Those columns initially showed up in this check.  Now it should

In [23]:
for col in df.columns:
    if df[col].isna().any():
        print(col)

Did it print anything? No? 
Good.

The next thing I want to take into consideration is playoff games.

From my years of watching the NBA I feel like the playoffs are an entirely different entity than the regular season.  For that reason I won't be attempting to predict post season games at this point and because of that I don't want to include them in my data set.  

The first and quickest way to account for this is by removing any row where either the home team or the away team has played 82 games.  Since I went through the painstaking (again two days of digging) effort to ensure games were getting tracked correctly I'm confident that removing all games over 82 will be the post season.

There are 3 cases where there will not be 82 games in the NBA Regular Season:

2011-2012 - The lockout caused the season to not start until Christmas day and shortened the season to 66 games.  In this case I will remove all games over 66 where the season is 2012
2019-2020 - The pandemic caused a stoppage in play starting in March before the season was resumed in the Orlando bubble in July.  For this season I will be removing all games in the bubble.  That situation was such an outlier I don't want it to impact predictions for future games.
2020-2021 - As a result of the bubble running until mid october the 2020-2021 season did not start until December and was a shortened 72 game season.  I will do a similar filter to remove all games in the 2021 season where the games played is higher than 72.

Let's clear out what we know

In [24]:
#Let's clear out anything from the Lockout season
df = df.loc[ (df.Season != 2012) | (df.Season == 2012) & (df.Date < '2012-04-28')]

In [25]:
#Let's clear out anything from the Covid Bubble
df = df.loc[(df.Season != 2020) | (df.Season == 2020) & (df.Date < '2020-03-12')]

In [26]:
#The shorted 2021 season had less than 82 games so we can clear that out as well
df = df.loc[(df.Season != 2021) | (df.Season == 2021) & (df.Date < '2021-05-22')]

Now that post season games from abnormal seasons have been removed, lets check if there are any other games missing by seeing if there are any teams playing their 83rd game of hte season and the other team is under 82 - that should be a clear sign that something is wrong

In [27]:
test = df.loc[((df.HomeGamesPlayed >= 82) & (df.AwayGamesPlayed < 82)) | ((df.HomeGamesPlayed < 82) & (df.AwayGamesPlayed >= 82))]
test[['Season','Date','HomeTeam', 'HomeWins', 'HomeLosses', 'HomeGamesPlayed','AwayTeam','AwayWins','AwayLosses','AwayGamesPlayed']].head(83)
#There should not be a situation where one team has 82 games and another team doesnt.

,Season,Date,HomeTeam,HomeWins,HomeLosses,HomeGamesPlayed,AwayTeam,AwayWins,AwayLosses,AwayGamesPlayed
6245,2013,2013-04-20,NYK,54.0,28.0,82.0,BOS,41.0,40.0,81.0
6251,2013,2013-04-21,IND,49.0,32.0,81.0,ATL,44.0,38.0,82.0

In [28]:
df = df[df.HomeGamesPlayed < 82]

In [29]:
df =  df[df.AwayGamesPlayed < 82]

In [31]:
for season in range(2009, 2024):
    for team in np.sort(df["HomeTeam"].unique()):
        games_in_season = df.loc[((df.HomeTeam == team) | (df.AwayTeam == team)) & (df.Season == season)]

        if games_in_season.shape[0] == 0:
            continue

        total_games = 81
        if season == 2020:
            continue
        if season == 2012:
            total_games = 65
        if season == 2021:
            total_games = 71
                    
        
        last_game_in_season = games_in_season.iloc[-1]
        
        if last_game_in_season.HomeTeam == team:
            if last_game_in_season.HomeGamesPlayed < total_games:
                print(f'{team} in {season} is missing {total_games - last_game_in_season.HomeGamesPlayed} games')
        else:
            if last_game_in_season.AwayGamesPlayed < total_games:
                print(f'{team} in {season} is missing {total_games - last_game_in_season.AwayGamesPlayed } games')

BOS in 2013 is missing 1.0 games
IND in 2013 is missing 1.0 games

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17806 entries, 0 to 19076
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 17806 non-null  int64
 1   Season             17806 non-null  int64
 2   Date               17806 non-null  object
 3   Time               17806 non-null  object
 4   HomeTeamId         17806 non-null  int64
 5   HomeTeam           17806 non-null  object
 6   HomeScore          17806 non-null  int64
 7   AwayTeamId         17806 non-null  int64
 8   AwayTeam           17806 non-null  object
 9   AwayScore          17806 non-null  int64
 10  OverTime           17806 non-null  int64
 11  Latitude           17806 non-null  float64
 12  Longitude          17806 non-null  float64
 13  TravelDistance     17806 non-null  float64
 14  AwayWins           17806 non-null  float64
 15  AwayLosses         17806 non-null  float64
 16  AwayStreak         17806 non-null  float64
 17  AwayGamesPlayed    17806 non-null  float64
 18  AwayWinPercentage  17806 non-null  float64
 19  HomeWins           17806 non-null  float64
 20  HomeLosses         17806 non-null  float64
 21  HomeStreak         17806 non-null  float64
 22  HomeGamesPlayed    17806 non-null  float64
 23  HomeWinPercentage  17806 non-null  float64
dtypes: float64(13), int64(7), object(4)
memory usage: 3.4+ MB

In [39]:
clean_data = df.drop(columns=['Latitude', 'Longitude', 'HomeWins', 'HomeLosses', 'AwayWins', 'AwayLosses'])

In [40]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17806 entries, 0 to 19076
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 17806 non-null  int64
 1   Season             17806 non-null  int64
 2   Date               17806 non-null  object
 3   Time               17806 non-null  object
 4   HomeTeamId         17806 non-null  int64
 5   HomeTeam           17806 non-null  object
 6   HomeScore          17806 non-null  int64
 7   AwayTeamId         17806 non-null  int64
 8   AwayTeam           17806 non-null  object
 9   AwayScore          17806 non-null  int64
 10  OverTime           17806 non-null  int64
 11  TravelDistance     17806 non-null  float64
 12  AwayStreak         17806 non-null  float64
 13  AwayGamesPlayed    17806 non-null  float64
 14  AwayWinPercentage  17806 non-null  float64
 15  HomeStreak         17806 non-null  float64
 16  HomeGamesPlayed    17806 non-null  float64
 17  HomeWinPercentage  17806 non-null  float64
dtypes: float64(7), int64(7), object(4)
memory usage: 2.6+ MB

In [41]:
clean_data.to_csv('Data/game_data_clean.csv', index=False)